### ISSUE TITLE
stream_error: :closed

### ISSUE THREAD

**Issue by mairbek** [elixir-grpc/grpc#138]
**Describe the bug**

we are getting this error in the `GRPC.Stub`

```
Task #PID<0.2576.0> started from #PID<0.2569.0> terminating
** (CaseClauseError) no case clause matching: {:error, %GRPC.RPCError{message: ":stream_error: :closed", status: 13}}
    (grpc) lib/grpc/stub.ex:456: GRPC.Stub.recv_body/5
    (grpc) lib/grpc/stub.ex:427: GRPC.Stub.do_recv/2
    (micro) lib/micro/adapters/simple_grpc/client/caller.ex:55: 
```

**To Reproduce**
I'm trying to figure out but hard to reproduce with an example.

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Protos**
If applicable, add protos to help explain your problem.

**Versions:**
- OS:
- Erlang:
- Elixir:
- mix.lock(grpc, gun, cowboy, cowlib):

**Additional context**

**Comment by mairbek** [comment]
Turns out that the correct version of cowlib wasn't resolved. Closing this.
